on:
  release:
    types: [created]

name: Deploy package
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Build and publish
        run: |
         npm ci
         npm run build
         cd build
         npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_REF_NAME: ${{ github.ref_name }}
      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}